server:
  host: 127.0.0.1
  port: 8000

app:
  dbType: mysql
  runtimeRootPath: runtime/
  imageSavePath: upload/images

log:
  logSavePath: logs/
  logSaveName: log
  logFileExt: log
  timeFormat: 20060102

mysql:
  host: 127.0.0.1
  port: 3360
  username: root
  password: 123456
  dbName: chat_room

redis:
  host: 127.0.0.1
  port: 6379
  password:

jwt:
  secretKey: jkfsunl79
  expiration: 1800
  issuer: chat-room

mq:
  host: localhost
  username: guest
  password: guest
  port: 5672

