server:
  port: 8000

app:
  dbType: mysql
  runtimeRootPath: runtime/
  imageSavePath: upload/images

log:
  logSavePath: logs/
  logSaveName: log
  logFileExt: log
  timeFormat: 20060102

mysql:
  username: root
  password: 123456
  host: 127.0.0.1:3360
  dbName: chat_room

redis:
  host: 127.0.0.1:6379
  password: 123456
  maxIdle: 30
  maxActive: 30
  idleTimeout: 100

jwt:
  secretKey: jkfsunl79


